"""DK4 — `create-domain` and the real second-domain proof.

Part 1 (commit A — the scaffold):
  - `render()` produces the six files, each with the name substituted and no template marker
    left; a freshly generated domain validates with 0 FAIL / 0 WARN, its layout and lazy
    backend checks pass, its generated test passes, and both policies reach the goal — all
    in a throwaway copy, never in the working tree;
  - `create_domain` writes NEW files only: it refuses an existing directory, an existing test
    file, an invalid/reserved/registered name, and a target outside the repository, and it
    never touches `domains/registry.py` (the registry lines are printed);
  - the CLI subcommand: exit 0 with the next steps, exit 1 on a refusal.

Part 2 (commit B — the proof, `tests/fixture_lamp/`): the fixture was generated by the exact
command a user runs (`python -m maaos create-domain lamp --target tests/fixture_lamp`, commit
A is byte-identical to the generator's output) and then changed ONLY through the documented
extension points to a small deterministic domain with a designed physical failure:
  - the fixture's file set equals the scaffold's and every `# TODO(author)` extension point
    is still present (evidence that only extension points were edited);
  - the lamp domain validates with 0 FAIL / 0 WARN; the sticky lamp makes an applicable
    `TurnOn` fail physically; `symbolic_primary` halts on the repeated failure with the
    typed discrepancies, `advisory_two_track` recovers through the recovery advice
    (`Nudge`, then `TurnOn`) and reaches the goal;
  - AST import pins per role (the fixture's `types.py`/`model.py`/`environment.py` import
    only stdlib + shared + kit + siblings; `__init__.py` only app/kit/shared + siblings), the
    guard's own role scanner agrees on a copy placed under `domains/`, and a subprocess pin
    that a full episode loads no `domain`/`symbolic`/`nl`/`app.box_push_v1`/`app.comparator`/
    backend module.

Offline and deterministic.
"""
from __future__ import annotations

import ast
import contextlib
import io
import json
import os
import pathlib
import shutil
import subprocess
import sys
import tempfile
import unittest

_REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from app.validation import Status, check_layout, check_lazy_backend, validate_domain  # noqa: E402
from domains.registry import REGISTRY                                    # noqa: E402
from maaos.cli import main                                               # noqa: E402
from maaos.scaffold import ScaffoldError, check_name, create_domain, render  # noqa: E402
from tests.test_no_backend_imports import (                              # noqa: E402
    FORBIDDEN_PREFIXES,
    domain_role_violations,
    imported_modules,
)

_TEMPLATES = _REPO_ROOT / "maaos" / "templates"
_PACKAGE_FILES = ("__init__.py", "types.py", "model.py", "environment.py", "README.md")


def _scratch_repo(stack) -> pathlib.Path:
    """A throwaway copy of the packages a generated domain imports, so a scaffold can be
    generated, imported and validated without touching the working tree."""
    root = pathlib.Path(stack.enter_context(tempfile.TemporaryDirectory()))
    for package in ("shared", "runtime", "app", "kit", "domains", "maaos"):
        shutil.copytree(_REPO_ROOT / package, root / package,
                        ignore=shutil.ignore_patterns("__pycache__"))
    for package in ("domain", "symbolic", "nl"):          # domains.registry imports BoxPush
        shutil.copytree(_REPO_ROOT / package, root / package,
                        ignore=shutil.ignore_patterns("__pycache__"))
    (root / "tests").mkdir()
    (root / "tests" / "__init__.py").write_text("", encoding="utf-8")
    shutil.copy(_REPO_ROOT / "tests" / "test_no_backend_imports.py", root / "tests")
    return root


def _run_in(root: pathlib.Path, script: str) -> dict:
    env = dict(os.environ, PYTHONPATH=str(root), SDL_VIDEODRIVER="dummy")
    completed = subprocess.run(
        [sys.executable, "-B", "-c", script], cwd=root, env=env,
        capture_output=True, text=True, timeout=300,
    )
    if completed.returncode != 0:
        raise AssertionError(completed.stdout + completed.stderr)
    return json.loads(completed.stdout.strip().splitlines()[-1])


# ═══ part 1: the scaffold ═══════════════════════════════════════════════════════════════

class TestRender(unittest.TestCase):
    def test_six_files_with_the_name_substituted_and_no_marker_left(self):
        files = render("warehouse", package_import="domains.warehouse",
                       test_module="tests.test_domain_warehouse")
        self.assertEqual(set(files), set(_PACKAGE_FILES) | {"tests/test_domain_warehouse.py"})
        for path, content in files.items():
            self.assertNotIn("__NAME__", content, path)
            self.assertNotIn("__PACKAGE_IMPORT__", content, path)
            self.assertNotIn("__TEST_MODULE__", content, path)
            self.assertIn("warehouse", content, path)
        self.assertIn("from domains.warehouse import DOMAIN", files["tests/test_domain_warehouse.py"])
        self.assertIn('name="warehouse"', files["__init__.py"])
        for template in _TEMPLATES.glob("*.py.tmpl"):
            self.assertIn("TODO(author)", template.read_text(encoding="utf-8"), template.name)

    def test_generated_python_parses_and_follows_the_module_roles(self):
        files = render("lamp", package_import="domains.lamp", test_module="tests.test_domain_lamp")
        for path, content in files.items():
            if path.endswith(".py"):
                ast.parse(content, filename=path)
        with contextlib.ExitStack() as stack:
            root = pathlib.Path(stack.enter_context(tempfile.TemporaryDirectory()))
            pkg = root / "domains" / "lamp"
            pkg.mkdir(parents=True)
            (root / "domains" / "__init__.py").write_text("", encoding="utf-8")
            for name in _PACKAGE_FILES:
                (pkg / name).write_text(files[name], encoding="utf-8")
            (root / "tests").mkdir()
            (root / "tests" / "test_no_backend_imports.py").write_text(
                "DOMAIN_ENVIRONMENT_MODULES = frozenset()\n", encoding="utf-8")
            self.assertEqual(domain_role_violations(root), [])
            self.assertEqual([f.status for f in check_layout("lamp", repo_root=root)],
                             [Status.PASS, Status.PASS])


class TestAFreshScaffoldValidatesOutOfTheBox(unittest.TestCase):
    def test_generate_import_validate_and_run_in_a_scratch_copy(self):
        with contextlib.ExitStack() as stack:
            root = _scratch_repo(stack)
            created = create_domain("fresh", repo_root=root)
            self.assertEqual(created.package_import, "domains.fresh")
            self.assertEqual(len(created.written), 6)
            self.assertIn("from domains.fresh import DOMAIN as _FRESH", created.next_steps(root))
            # the registry is never edited
            self.assertEqual((root / "domains" / "registry.py").read_text(encoding="utf-8"),
                             (_REPO_ROOT / "domains" / "registry.py").read_text(encoding="utf-8"))
            report = _run_in(root, (
                "import json\n"
                "from app.validation import Status, validate_domain, check_layout, check_lazy_backend\n"
                "from app.assembly import assemble_loop\n"
                "from shared.orchestration_config import OrchestrationConfig, OrchestrationPolicy\n"
                "from domains.fresh import DOMAIN\n"
                "r = validate_domain(DOMAIN)\n"
                "outcomes = {p.value: assemble_loop(DOMAIN, config=OrchestrationConfig(policy=p)).run().outcome.value\n"
                "            for p in OrchestrationPolicy}\n"
                "print(json.dumps({'fail': [f.code for f in r.findings if f.status is Status.FAIL],\n"
                "                  'warn': [f.code for f in r.findings if f.status is Status.WARN],\n"
                "                  'skipped': [f.code for f in r.findings if f.status is Status.SKIPPED],\n"
                "                  'layout': [f.status.value for f in check_layout('fresh', repo_root=__import__('pathlib').Path('.').resolve())],\n"
                "                  'lazy': check_lazy_backend('fresh', repo_root=__import__('pathlib').Path('.').resolve()).status.value,\n"
                "                  'outcomes': outcomes}))\n"
            ))
            self.assertEqual(report["fail"], [])
            self.assertEqual(report["warn"], [])
            self.assertEqual(report["skipped"], ["DK017", "DK071"])
            self.assertEqual(report["layout"], ["PASS", "PASS"])
            self.assertEqual(report["lazy"], "PASS")
            self.assertEqual(report["outcomes"],
                             {"symbolic_primary": "goal_reached", "advisory_two_track": "goal_reached"})
            env = dict(os.environ, PYTHONPATH=str(root), SDL_VIDEODRIVER="dummy")
            completed = subprocess.run(
                [sys.executable, "-B", "-m", "unittest", "tests.test_domain_fresh"],
                cwd=root, env=env, capture_output=True, text=True, timeout=300,
            )
            self.assertEqual(completed.returncode, 0, completed.stderr)
            self.assertIn("OK", completed.stderr)


class TestCreateDomainWritesNewFilesOnly(unittest.TestCase):
    def test_refusals(self):
        for bad in ("Warehouse", "_x", "class", "not a name", "9lives"):
            with self.subTest(name=bad), self.assertRaises(ScaffoldError):
                check_name(bad)
        with self.assertRaisesRegex(ScaffoldError, "already registered"):
            check_name("box_push", REGISTRY)
        with contextlib.ExitStack() as stack:
            root = pathlib.Path(stack.enter_context(tempfile.TemporaryDirectory()))
            (root / "domains" / "taken").mkdir(parents=True)
            with self.assertRaisesRegex(ScaffoldError, "already exists"):
                create_domain("taken", repo_root=root)
            (root / "tests").mkdir()
            (root / "tests" / "test_domain_other.py").write_text("", encoding="utf-8")
            with self.assertRaisesRegex(ScaffoldError, "already exists"):
                create_domain("other", repo_root=root)
            self.assertFalse((root / "domains" / "other").exists())
            with self.assertRaisesRegex(ScaffoldError, "inside the repository"):
                create_domain("far", repo_root=root, target=pathlib.Path(tempfile.gettempdir()) / "far_away")

    def test_target_writes_elsewhere_with_the_dotted_import(self):
        with contextlib.ExitStack() as stack:
            root = pathlib.Path(stack.enter_context(tempfile.TemporaryDirectory()))
            (root / "tests").mkdir()
            created = create_domain("lamp", repo_root=root, target=pathlib.Path("tests/fixture_lamp"))
            self.assertEqual(created.package_import, "tests.fixture_lamp")
            self.assertTrue((root / "tests" / "fixture_lamp" / "__init__.py").is_file())
            test = (root / "tests" / "test_domain_lamp.py").read_text(encoding="utf-8")
            self.assertIn("from tests.fixture_lamp import DOMAIN", test)
            self.assertIn("not registered", created.next_steps(root))

    def test_the_working_tree_is_never_touched_by_these_tests(self):
        self.assertFalse((_REPO_ROOT / "domains" / "fresh").exists())
        self.assertFalse((_REPO_ROOT / "tests" / "test_domain_fresh.py").exists())


class TestCliCreateDomain(unittest.TestCase):
    def _main(self, *argv):
        out, err = io.StringIO(), io.StringIO()
        with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
            try:
                code = main(list(argv))
            except SystemExit as exit_:
                code = exit_.code
        return code, out.getvalue(), err.getvalue()

    def test_a_registered_name_is_refused_with_exit_one(self):
        code, _, err = self._main("create-domain", "box_push")
        self.assertEqual(code, 1)
        self.assertIn("already registered", err)

    def test_an_invalid_name_is_refused_with_exit_one(self):
        code, _, err = self._main("create-domain", "Not-Valid")
        self.assertEqual(code, 1)
        self.assertIn("identifier", err)

    def test_an_existing_target_is_refused(self):
        code, _, err = self._main("create-domain", "lamp", "--target", "tests/fixture_lamp")
        self.assertEqual(code, 1)
        self.assertIn("already exists", err)


# ═══ part 2: the lamp proof (commit B) ═════════════════════════════════════════════════

_FIXTURE = _REPO_ROOT / "tests" / "fixture_lamp"


class TestTheFixtureWasChangedOnlyThroughExtensionPoints(unittest.TestCase):
    def test_file_set_equals_the_scaffolds_and_every_extension_point_survives(self):
        self.assertEqual({p.name for p in _FIXTURE.iterdir() if p.name != "__pycache__"},
                         set(_PACKAGE_FILES))
        scaffold = render("lamp", package_import="tests.fixture_lamp", test_module="tests.test_domain_lamp")
        for name in _PACKAGE_FILES:
            if name.endswith(".py"):
                markers = [line.strip() for line in scaffold[name].splitlines() if "TODO(author)" in line]
                text = (_FIXTURE / name).read_text(encoding="utf-8")
                self.assertTrue(markers, name)
                for marker in markers:
                    self.assertIn(marker.split("TODO(author)")[0] + "TODO(author)", text, f"{name}: {marker}")

    def test_imports_follow_the_module_roles_and_the_guard_agrees(self):
        allowed = {"__future__", "dataclasses", "enum", "json", "typing", "shared", "kit"}
        for name in ("types.py", "model.py", "environment.py"):
            for module, lineno in imported_modules(_FIXTURE / name):
                self.assertIn(module.split(".")[0], allowed, f"{name}:{lineno} imports {module}")
        for module, lineno in imported_modules(_FIXTURE / "__init__.py"):
            self.assertIn(module.split(".")[0], allowed | {"app"}, f"__init__.py:{lineno} imports {module}")
        with contextlib.ExitStack() as stack:
            root = pathlib.Path(stack.enter_context(tempfile.TemporaryDirectory()))
            (root / "domains").mkdir()
            (root / "domains" / "__init__.py").write_text("", encoding="utf-8")
            shutil.copytree(_FIXTURE, root / "domains" / "lamp", ignore=shutil.ignore_patterns("__pycache__"))
            (root / "tests").mkdir()
            (root / "tests" / "test_no_backend_imports.py").write_text(
                "DOMAIN_ENVIRONMENT_MODULES = frozenset()\n", encoding="utf-8")
            self.assertEqual(domain_role_violations(root), [])
            self.assertEqual([f.status for f in check_layout("lamp", repo_root=root)], [Status.PASS, Status.PASS])


class TestTheLampDomainIsTheSecondDomainProof(unittest.TestCase):
    """The success criterion, mechanically: a small deterministic domain with a designed
    physical failure, built from the scaffold through its extension points, validated and
    run without any edit under runtime/, shared/, kit/ or app/ (the change-set pin is the
    reviewer's `git diff --name-only main...HEAD` before merge)."""

    @classmethod
    def setUpClass(cls):
        from tests.fixture_lamp import DOMAIN
        cls.domain = DOMAIN

    def test_validates_with_no_fail_and_no_warn(self):
        report = validate_domain(self.domain)
        self.assertEqual([f.code for f in report.findings if f.status is Status.FAIL], [], report.render())
        self.assertEqual([f.code for f in report.findings if f.status is Status.WARN], [], report.render())
        self.assertEqual([f.code for f in report.findings if f.status is Status.SKIPPED], ["DK017", "DK071"])

    def test_symbolic_primary_halts_on_the_stuck_switch_with_typed_evidence(self):
        from app.assembly import assemble_loop
        from runtime.loop import EpisodeOutcome
        from shared.discrepancy import DiscrepancyKind
        from shared.orchestration_config import OrchestrationConfig, OrchestrationPolicy
        loop = assemble_loop(self.domain, config=OrchestrationConfig(policy=OrchestrationPolicy.SYMBOLIC_PRIMARY))
        episode = loop.run()
        self.assertIs(episode.outcome, EpisodeOutcome.HALTED_REPEATED_FAILURE)
        self.assertEqual([(str(d.call), d.kind) for d in episode.discrepancies],
                         [("TurnOn(l2)", DiscrepancyKind.EXECUTION_FAILURE_OF_APPLICABLE_SKILL)] * 3)
        self.assertEqual(loop.executive_steps_charged, 4)

    def test_advisory_two_track_recovers_through_the_advice_and_reaches_the_goal(self):
        from app.assembly import assemble_loop
        from runtime.loop import EpisodeOutcome
        from shared.orchestration_config import ExecutiveDecision, OrchestrationConfig, OrchestrationPolicy
        loop = assemble_loop(self.domain, config=OrchestrationConfig(policy=OrchestrationPolicy.ADVISORY_TWO_TRACK))
        episode = loop.run()
        self.assertIs(episode.outcome, EpisodeOutcome.GOAL_REACHED)
        decisions = [e.decision for e in episode.history.entries]
        self.assertEqual(decisions.count(ExecutiveDecision.REQUEST_PROPOSAL), 1)
        executed = [str(e.selected_call) for e in episode.history.entries if e.execution is not None]
        self.assertEqual(executed[-2:], ["Nudge(l2)", "TurnOn(l2)"])
        self.assertEqual(len(episode.discrepancies), 3)
        self.assertTrue(loop.env.export_full_state().lit == frozenset({"l1", "l2"}))


class TestTheLampDomainRunsWithoutBoxPushOrTheBackend(unittest.TestCase):
    def test_a_full_episode_under_both_policies_loads_no_boxpush_or_backend_module(self):
        forbidden = sorted(FORBIDDEN_PREFIXES | {"domain", "symbolic", "nl"})
        script = (
            "import json, sys\n"
            "from app.assembly import assemble_loop\n"
            "from shared.orchestration_config import OrchestrationConfig, OrchestrationPolicy\n"
            "from tests.fixture_lamp import DOMAIN\n"
            "outcomes = {p.value: assemble_loop(DOMAIN, config=OrchestrationConfig(policy=p)).run().outcome.value\n"
            "            for p in OrchestrationPolicy}\n"
            f"roots = {forbidden!r}\n"
            "loaded = sorted(m for m in sys.modules if m.split('.')[0] in roots\n"
            "                or m in ('app.box_push_v1', 'app.comparator'))\n"
            "print(json.dumps({'outcomes': outcomes, 'loaded': loaded}))\n"
        )
        report = _run_in(_REPO_ROOT, script)
        self.assertEqual(report["loaded"], [], report)
        self.assertEqual(report["outcomes"]["advisory_two_track"], "goal_reached")


if __name__ == "__main__":
    unittest.main()
