"""Domain `lamp` — the declaration (COMPOSITION role).

This is the one module of the package that may import `app` (the composition layer, which
sits above the runtime) and the sibling `environment`. It declares `DOMAIN`, the object
`domains/registry.py` registers. Everything else stays on the symbolic side.

Generated by `python -m maaos create-domain lamp`. Everything an author changes is
marked `# TODO(author)`; the untouched scaffold already passes `validate-domain`.
"""
from __future__ import annotations

from app.domain_package import DomainExamples, DomainPackage
from kit import DefaultProposalComparator, DerivedDomainServices, ProjectionTrack
from shared.contracts import AdvisoryProposal
from shared.discrepancy import ExecutionDiscrepancy

from .environment import make_environment
from .model import MODEL, SymbolicState
from .types import Call, Op, State, Task

# ── tasks ─────────────────────────────────────────────────────────────────────────────
# TODO(author): declare the named tasks of the domain (at least one) and the default.
TASKS = {
    "light_all": Task(task_id="light_all", description="Light both lamps.", lamps=("l1", "l2")),
}

# ── examples for validate-domain (optional, recommended) ──────────────────────────────
# TODO(author): a call naming an identity the initial state LACKS, and a grounded call whose
# preconditions FAIL in the initial state.
EXAMPLES = DomainExamples(
    ungrounded_call=Call(Op.TURN_ON, "ghost"),
    inapplicable_call=Call(Op.TURN_OFF, "l1"),
)


# ── recovery advice (optional) ────────────────────────────────────────────────────────
def recover(discrepancy: ExecutionDiscrepancy[Call]) -> tuple[Call, ...]:
    """Advice after a physically failed call. It is ADVICE: every call it returns passes the
    same grounding/applicability gates and the same executor as any other call.

    When it is consulted: under advisory_two_track, after the SAME (state, call) has failed
    `repeated_failure_threshold` times (3 by default) — the first failures are retried, the
    symbolic model is never patched. The tuple you return is executed IN ORDER before the
    planner runs again. `discrepancy` carries `.call` (the failed call), `.kind`, `.message`
    and the predicted/observed keys; the environment's hidden reason is NOT visible here.

    TODO(author): return the calls that should be tried after `discrepancy.call` failed
    physically; return () to advise nothing (the advisory policy then halts like the
    symbolic-primary one)."""
    failed = discrepancy.call
    if failed.op is Op.TURN_ON:
        return (Call(Op.NUDGE, failed.lamp_id), Call(Op.TURN_ON, failed.lamp_id))
    return ()


DOMAIN: DomainPackage[State, SymbolicState, Call, Task, AdvisoryProposal] = DomainPackage(
    name="lamp",
    tasks=TASKS,
    default_task="light_all",
    environment=make_environment,
    services=lambda task: DerivedDomainServices(MODEL, apply_world=MODEL.apply_world),
    symbolic_track=lambda: ProjectionTrack(MODEL.project),
    recovery_provider=recover,
    comparator=lambda: DefaultProposalComparator[Call, AdvisoryProposal](),
    reasoning_track=None,            # an offline advisory track may be declared later
    examples=EXAMPLES,
)

__all__ = ["DOMAIN", "EXAMPLES", "TASKS", "recover"]
